### ISSUE TITLE
Enhancement: add some simple issue templates to the project

### ISSUE THREAD

**Issue by Senipah** [SSlinky/markdoc#1]
### Is your proposal related to a problem?

It would be good to add some issue templates to this repository to facilitate a standardised method of creating bug reports, feature requests, user support etc.

### Describe the solution you'd like

The following link shows how to create issue templates:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I have some example's [here ](https://github.com/Senipah/VBA-Better-Array/tree/master/.github/ISSUE_TEMPLATE) though I'm sure other better ones are available. Would just be nice to have a template to complete to try and ensure submissions are sufficiently detailed.

### Describe alternatives you've considered

User stories / bugs could be tracked using other collaborative tools but IMO Github would be the best place for now.

### Additional context

N/A

**Comment by SSlinky** [comment]
Agree. Happy for you to write some basic ones.
