### ISSUE TITLE
Enhancement/RFC/Proposal: Add support for Rubberduck folder Navigation

### ISSUE THREAD

**Issue by Senipah** [SSlinky/markdoc#2]
### Is your proposal related to a problem?

At the moment importing the whole project is a bit of a chore. One of the pain points I noticed was reconciling whether I had imported all files from all sub directories.

### Describe the solution you'd like

To aid in reconciling file imports and to aid in general project navigation, I'd like to add support for [Rubberduck folder navidations](https://github.com/rubberduck-vba/Rubberduck/wiki/Using-@Folder-Annotations).

This allows Rubberduck users to more easily check that the structure of the project import matches that of the repository. It also generally improves the project navigation experience when using the Rubberduck project navigator.

### Describe alternatives you've considered

Ultimately a refined import process for end users should be considered. The proposed solution would act as a temporary measure mainly for the benefit of project maintainers. 

### Additional context

N/A

**Comment by SSlinky** [comment]
I've been synchronising Word and the project by simply creating an entirely new document each time I've made some significant changes. I will make small syntactical corrections in the IDE but these changes need to be copied to the project or they get lost.

To import the classes and modules, I simply do a search on *.??s which gives me all .bas and .cls files. Just select them all and drag them into the new document. Not the best solution for end users, obviously, but certainly not onerous for development.

**Comment by Senipah** [comment]
TBH you're right that just adding a filter to search for `*.` does make it fairly simple to import all the files. not sure why I was trying to import each one individually 🙃 

That said, I don't believe there to be any downside to adding support for Rubberduck folder navigation and it would add a better UX for those that use it, so I will submit a PR for this feat.
